### ISSUE TITLE
Feature Request(s): Making multiplier-function in Multiplier Strategy return a double

### ISSUE THREAD

**Issue by anbclausen** [anbclausen/pokelin#15]
**I'm requesting the following features**
- Making multiplier-function in Multiplier Strategy return a double instead of the enum: The field _multiplier_ on EffectLevel is never used. I don't think this was intended. I want to correct the error. 

**Assignment**
- [x] Please assign this to me.
- [ ] I would like someone else to implement this.

**Comment by frederik1904** [comment]
This was actually intended behavior, as this gives the possibility of giving the enums names, making them easier to print in the future.

**Comment by anbclausen** [comment]
@frederik1904 I want to keep the enum, but make the multipler return enum.multiplier. I imagine it being used like:
```
fun attack() {
  something * multiplierStrategy.multiplier * something_else
}
```

**Comment by frederik1904** [comment]
If you rewrite it to return a double, then you would have to scan through the enums when looking for what type you ended up getting (if this was needed in the future) and as I see it we would probably want some way of knowing this. I would say that "only" returning the value would probably end up bloating the code base.

**Comment by anbclausen** [comment]
Alright. Good point. :) Closing the issue.
